### PR TITLE
Delegate equals comparison in Record to Field

### LINKED ISSUE #1975: Delegate equals comparison in Record to Field
Currently, Record.equals directly compares the `valueBox` and `name` of each field. This makes it impossible to override that functionality in individual Fields. Because of this, PatternField does not work properly in this regard.

The proposed solution is to delegate the comparison to the individual Field, using the current code as the default.

### PR DESCRIPTION
**Pull request by eltimn**
Fixes #1975

### CODE REVIEW

File: persistence/mongodb-record/src/main/scala/net/liftweb/mongodb/record/BsonRecord.scala [hunk 1]
```diff
@@ -57,6 +57,7 @@ trait BsonRecord[MyType <: BsonRecord[MyType]] extends Record[MyType] {
   /**
     * Pattern.equals doesn't work properly so it needs a special check. If you use PatternField, be sure to override equals with this.
     */
+  @deprecated("PatternField now has a properly functioning `equals` method.", "3.4.0")
```
Comment (farmdawgnation) [inline persistence/mongodb-record/src/main/scala/net/liftweb/mongodb/record/BsonRecord.scala]:
```suggestion
  @deprecated("PatternField now has a properly functioning `equals` method.", "3.4.1")
```

**Comment by eltimn** [comment]
Uh, I just noticed that commit suggestion button. I haven't used that yet. Looks really handy.
