### PR TITLE
Log if JSON parsing fails when handling a jsonCall invocation.

### LINKED ISSUE #1615: We don't indicate any sort of error if you make an AJAX request to an endpoint requiring JSON with invalid JSON
We ran into an annoying edge case in how we handle JSON AJAX requests.

We were using `SHtml.jsonCall` to wire up some stuff on the client to the server. This is all fine and dandy until you submit something that doesn't result in proper JSON to the function name. No error whatsoever is generated on the server or the client.

That... should probably be fixed.

### PR DESCRIPTION
**Pull request by farmdawgnation**
This PR is designed to address an issue where the call sent to a function wired up to a `jsonCall` isn't something that the JSON parser can actually parse. This tends to happen in cases where developers are doing some custom things with the `jsonCall` system - a bit more custom than just wiring it up to a button directly in a CSS transform.

To test this, you can set up a local Lift project and bind a JSON call to the browser somewhere, then invoke it from the console.

screen shot 2015-05-23 at 11 08 33 am

In my code, I had it print what it got from the client if it succeeded. If it failed, the framework would log its error to the console. Like so:

screen shot 2015-05-23 at 11 08 24 am

closes #1615

### CODE REVIEW

File: web/webkit/src/main/scala/net/liftweb/http/SHtml.scala [hunk 1]
```diff
@@ -169,6 +169,21 @@ trait SHtml {
     ajaxCall_*(jsCalcValue, jsContext, SFuncHolder(func))
 
   /**
+   * A wrapper around parseOpt for use in the jsonCall variants that will notify the developer on the console when
+   * parseOpt is unsuccessful at parsing the JSON.
+  **/
+  private def parseOptOrLog(rawJsonText: String) = {
```
Comment (farmdawgnation) [inline web/webkit/src/main/scala/net/liftweb/http/SHtml.scala]: Is this something that'd be useful in the JSON parser itself?

**Comment by farmdawgnation** [comment]
@Shadowfiend Hey, so in the ticket that I mentioned above you requested an overload of `jsonCall` that allows you to feed in a fallback function to provide a hook for the developer to handle the case the JSON couldn't be parsed.

The problem with that is that it'll take us from three overloads of `jsonCall` to six unless we make breaking changes to the API or we're horribly inconsistent. I'm honestly not in love with the idea. I'm kind of thinking it may be worth waiting to see how common it is that people need to do this and say in the meantime use `ajaxCall` and parse your own JSON. If we find people asking for this a lot we can always come back and add it, but I'm not sure it's going to be useful enough weighed against the API complexity.

If you disagree we could take it to the ML and discuss there.

**Comment by farmdawgnation** [comment]
Still waiting for some feedback from ya here @Shadowfiend

File: web/webkit/src/main/scala/net/liftweb/http/SHtml.scala (hunk 1 above)
Comment (Shadowfiend) [inline web/webkit/src/main/scala/net/liftweb/http/SHtml.scala]: I think if this went into `lift-json` it would best be `parseOptOr(rawJsonText: String)(alternative: =>Option[JValue])` or something of the sort.

**Comment by Shadowfiend** [comment]
I think this is definitely good to start with, though I already know I'd probably want to customize that behavior. Logging doesn't tell the user anything, after all :)

**Comment by Shadowfiend** [comment]
Any chance we can merge master in here and get a good CI build?

**Comment by Shadowfiend** [comment]
The answer, apparently, was “yes, we can merge master, no, we can't get a good CI build” -.-

Anyway, :+1: let's get 'er goin'.
